name: Test records

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9.0-rc.1]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PIP
      run: |
        python -m pip install --upgrade pip
    - name: Setup Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        sh scripts/install.sh
    - name: Tests
      run: |
        sh scripts/unittest.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
    - name: Lint
      run: |
        sh scripts/lint.sh
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install PIP
          run: |
            python -m pip install --upgrade pip
            - name: Setup Cache
              uses: actions/cache@v2
              with:
                path: ~/.cache/pypoetry
                key: ${{ runner.os }}-pip-
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: Install dependencies
              run: |
                sh scripts/install.sh
      - name: run benchmark
          run: |
            sh scripts/benchmark.sh
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "added benchmark.rst"
            git push
